/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PublicidadeRouteImport } from './routes/publicidade'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIdRouteImport } from './routes/tv.$id'
import { Route as MovieIdRouteImport } from './routes/movie.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicidadeRoute = PublicidadeRouteImport.update({
  id: '/publicidade',
  path: '/publicidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdRoute = TvIdRouteImport.update({
  id: '/tv/$id',
  path: '/tv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/contactos': typeof ContactosRoute
  '/dmca': typeof DmcaRoute
  '/movies': typeof MoviesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/publicidade': typeof PublicidadeRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/movie/$id': typeof MovieIdRoute
  '/tv/$id': typeof TvIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/contactos': typeof ContactosRoute
  '/dmca': typeof DmcaRoute
  '/movies': typeof MoviesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/publicidade': typeof PublicidadeRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/movie/$id': typeof MovieIdRoute
  '/tv/$id': typeof TvIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/contactos': typeof ContactosRoute
  '/dmca': typeof DmcaRoute
  '/movies': typeof MoviesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/publicidade': typeof PublicidadeRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/movie/$id': typeof MovieIdRoute
  '/tv/$id': typeof TvIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anime'
    | '/contactos'
    | '/dmca'
    | '/movies'
    | '/privacidade'
    | '/publicidade'
    | '/search'
    | '/series'
    | '/sobre'
    | '/termos'
    | '/movie/$id'
    | '/tv/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anime'
    | '/contactos'
    | '/dmca'
    | '/movies'
    | '/privacidade'
    | '/publicidade'
    | '/search'
    | '/series'
    | '/sobre'
    | '/termos'
    | '/movie/$id'
    | '/tv/$id'
  id:
    | '__root__'
    | '/'
    | '/anime'
    | '/contactos'
    | '/dmca'
    | '/movies'
    | '/privacidade'
    | '/publicidade'
    | '/search'
    | '/series'
    | '/sobre'
    | '/termos'
    | '/movie/$id'
    | '/tv/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeRoute: typeof AnimeRoute
  ContactosRoute: typeof ContactosRoute
  DmcaRoute: typeof DmcaRoute
  MoviesRoute: typeof MoviesRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  PublicidadeRoute: typeof PublicidadeRoute
  SearchRoute: typeof SearchRoute
  SeriesRoute: typeof SeriesRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  MovieIdRoute: typeof MovieIdRoute
  TvIdRoute: typeof TvIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicidade': {
      id: '/publicidade'
      path: '/publicidade'
      fullPath: '/publicidade'
      preLoaderRoute: typeof PublicidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id': {
      id: '/tv/$id'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof TvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeRoute: AnimeRoute,
  ContactosRoute: ContactosRoute,
  DmcaRoute: DmcaRoute,
  MoviesRoute: MoviesRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  PublicidadeRoute: PublicidadeRoute,
  SearchRoute: SearchRoute,
  SeriesRoute: SeriesRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  MovieIdRoute: MovieIdRoute,
  TvIdRoute: TvIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
